### ISSUE TITLE
Correlation ID support is broken.

### ISSUE THREAD

**Issue by adib** [SAP/cf-python-logging-support#20]
As of version 3.1.1, log statements originating from Python's logging system are not recorded with the correlation ID as sent by the web client. The correlation ID did not appear in Kibana as a searchable value.

This affect loggers that are initialized as global variables — that is the `getLogger` call are likely to have executed prior to logger configuration to flask.

**Comment by gvachkov** [comment]
Hi adib, which framework support are you using - is it flask of sanic?

**Comment by adib** [comment]
Hi @gvachkov 

The framework is flask. The correlation ID value is provided in `X-Request-ID`.

**Comment by gvachkov** [comment]
Hi Adibowo, can we close this issue?

**Comment by adib** [comment]
@gvachkov Sadly I currently don't have time to replicate the issue into a sample project that can be placed here. But I've got a workaround by reordering the order of initialization. 

OTOH, that caused another issue with thread pools. Notably if logging is not done from within a flask context (i.e. from a sub-thread of a flask request), your logging component throws an exception.

**Comment by gvachkov** [comment]
I believe your issue is related to #12. We have provided fix and I have recently released a new version of the library v3.2.0.

Have in mind that with the latest version there are changes in logging, where few log fields related to user information are not populated by default. Check the [readme](https://github.com/SAP/cf-python-logging-support#logging-sensitive-data) for details.

I'm closing this issue, please reopen in case you still face issues.
